cloud:
  aws:
    region:
      static: us-east-1
    stack:
      auto: false
    credentials:
      access-key: AKIAQSM46CXPLPNRTBEB
      secret-key: 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
logging:
  level:
   com:
    amazonaws:
      internal:
        InstanceMetadataServiceResourceFetcher: error
      util:
        EC2MetadataUtils: error